name: Run Tests on Commit

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]

    - name: Run tests
      run: |
        pytest tests/